unit udm;

interface

uses
  Printers, Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, DB, StdCtrls,
  ExtCtrls, IBX.IBDatabase, IBX.IBQuery, IBX.IBCustomDataSet,
  IBX.IBTable, IBX.IBUpdateSQL, QuickRpt, QRCtrls, QRPrntr,
  QRAbout, Vcl.Imaging.jpeg, Vcl.Imaging.pngimage, grimgctrl, qrpctrls, acPNG;
type
  Tfdm = class(TForm)
    Bevel1: TBevel;
    Bevel2: TBevel;
    Bevel6: TBevel;
    Bevel7: TBevel;
    Label4: TLabel;
    IBQUsuarios: TIBQuery;
    DSQUsuarios: TDataSource;
    DSTUsuarios: TDataSource;
    IBTUsuarios: TIBTable;
    IBTUsuariosNUMERO: TIBStringField;
    IBTUsuariosVENCIMENTO: TDateField;
    IBTUsuariosVALOR: TFloatField;
    IBTUsuariosPORTADOR: TIBStringField;
    IBTUsuariosREGISTRO: TIBStringField;
    Label6: TLabel;
    IBQUsuariosNUMERO: TIBStringField;
    IBQUsuariosVENCIMENTO: TDateField;
    IBQUsuariosVALOR: TFloatField;
    IBQUsuariosPORTADOR: TIBStringField;
    IBQUsuariosREGISTRO: TIBStringField;
    IBTransaction1: TIBTransaction;
    Memo1: TMemo;
    IBDatabase1: TIBDatabase;
    Edit2: TEdit;
    IBQGENUSUARIOS: TIBQuery;
    IBQGENUSUARIOSGEN_ID: TLargeintField;
    IBTUsuariosNIVEL: TIBStringField;
    IBQUsuariosNIVEL: TIBStringField;
    Bevel41: TBevel;
    Bevel42: TBevel;
    Bevel43: TBevel;
    Label37: TLabel;
    Label38: TLabel;
    Label39: TLabel;
    IBQALTERACA: TIBQuery;
    IBTALTERACA: TIBTable;
    IBQGENALTERACA: TIBQuery;
    LargeintField3: TLargeintField;
    DSQGENALTERACA: TDataSource;
    DSQALTERACA: TDataSource;
    DSTALTERACA: TDataSource;
    IBTALTERACACODIGO: TIBStringField;
    IBTALTERACADESCRICAO: TIBStringField;
    IBTALTERACAQUANTIDADE: TFloatField;
    IBTALTERACAMEDIDA: TIBStringField;
    IBTALTERACAUNITARIO: TFloatField;
    IBTALTERACATOTAL: TFloatField;
    IBTALTERACADATA: TDateField;
    IBTALTERACATIPO: TIBStringField;
    IBTALTERACAPEDIDO: TIBStringField;
    IBTALTERACAITEM: TIBStringField;
    IBTALTERACACLIFOR: TIBStringField;
    IBTALTERACAVENDEDOR: TIBStringField;
    IBTALTERACACAIXA: TIBStringField;
    IBTALTERACAVALORICM: TFloatField;
    IBTALTERACAALIQUICM: TIBStringField;
    IBTALTERACAREGISTRO: TIBStringField;
    IBTALTERACACNPJ: TIBStringField;
    IBTALTERACAREFERENCIA: TIBStringField;
    IBTALTERACAHORA: TIBStringField;
    IBTALTERACADAV: TIBStringField;
    IBTALTERACATIPODAV: TIBStringField;
    IBTALTERACAENCRYPTHASH: TIBStringField;
    IBTALTERACACOO: TIBStringField;
    IBTALTERACACCF: TIBStringField;
    IBTALTERACADESCONTO: TIBBCDField;
    IBTALTERACASERIE: TIBStringField;
    IBTALTERACASUBSERIE: TIBStringField;
    IBTALTERACACFOP: TIBStringField;
    IBTALTERACACST_ICMS: TIBStringField;
    IBTALTERACACST_PIS_COFINS: TIBStringField;
    IBTALTERACAALIQ_PIS: TIBBCDField;
    IBTALTERACAALIQ_COFINS: TIBBCDField;
    IBTALTERACAOBS: TIBStringField;
    IBTALTERACASTATUS: TIBStringField;
    IBTALTERACAANVISA: TIntegerField;
    IBQALTERACACODIGO: TIBStringField;
    IBQALTERACADESCRICAO: TIBStringField;
    IBQALTERACAQUANTIDADE: TFloatField;
    IBQALTERACAMEDIDA: TIBStringField;
    IBQALTERACAUNITARIO: TFloatField;
    IBQALTERACATOTAL: TFloatField;
    IBQALTERACADATA: TDateField;
    IBQALTERACATIPO: TIBStringField;
    IBQALTERACAPEDIDO: TIBStringField;
    IBQALTERACAITEM: TIBStringField;
    IBQALTERACACLIFOR: TIBStringField;
    IBQALTERACAVENDEDOR: TIBStringField;
    IBQALTERACACAIXA: TIBStringField;
    IBQALTERACAVALORICM: TFloatField;
    IBQALTERACAALIQUICM: TIBStringField;
    IBQALTERACAREGISTRO: TIBStringField;
    IBQALTERACACNPJ: TIBStringField;
    IBQALTERACAREFERENCIA: TIBStringField;
    IBQALTERACAHORA: TIBStringField;
    IBQALTERACADAV: TIBStringField;
    IBQALTERACATIPODAV: TIBStringField;
    IBQALTERACAENCRYPTHASH: TIBStringField;
    IBQALTERACACOO: TIBStringField;
    IBQALTERACACCF: TIBStringField;
    IBQALTERACADESCONTO: TIBBCDField;
    IBQALTERACASERIE: TIBStringField;
    IBQALTERACASUBSERIE: TIBStringField;
    IBQALTERACACFOP: TIBStringField;
    IBQALTERACACST_ICMS: TIBStringField;
    IBQALTERACACST_PIS_COFINS: TIBStringField;
    IBQALTERACAALIQ_PIS: TIBBCDField;
    IBQALTERACAALIQ_COFINS: TIBBCDField;
    IBQALTERACAOBS: TIBStringField;
    IBQALTERACASTATUS: TIBStringField;
    IBQALTERACAANVISA: TIntegerField;
    Bevel44: TBevel;
    Bevel45: TBevel;
    Bevel46: TBevel;
    Label40: TLabel;
    Label41: TLabel;
    Label42: TLabel;
    DSQCAIXA: TIBQuery;
    IBTCAIXA: TIBTable;
    IBQGENCAIXA: TIBQuery;
    LargeintField4: TLargeintField;
    DSQGENCAIXA: TDataSource;
    DataSource2: TDataSource;
    DSTCAIXA: TDataSource;
    IBTCAIXADATA: TDateField;
    IBTCAIXACONTA: TIBStringField;
    IBTCAIXANOME: TIBStringField;
    IBTCAIXAHISTORICO: TIBStringField;
    IBTCAIXAENTRADA: TFloatField;
    IBTCAIXASAIDA: TFloatField;
    IBTCAIXASALDO: TFloatField;
    IBTCAIXAREGISTRO: TIBStringField;
    DSQCAIXADATA: TDateField;
    DSQCAIXACONTA: TIBStringField;
    DSQCAIXANOME: TIBStringField;
    DSQCAIXAHISTORICO: TIBStringField;
    DSQCAIXAENTRADA: TFloatField;
    DSQCAIXASAIDA: TFloatField;
    DSQCAIXASALDO: TFloatField;
    DSQCAIXAREGISTRO: TIBStringField;
    Bevel25: TBevel;
    Label15: TLabel;
    Bevel26: TBevel;
    Label16: TLabel;
    Bevel29: TBevel;
    Label19: TLabel;
    Bevel4: TBevel;
    Bevel9: TBevel;
    Bevel17: TBevel;
    Label5: TLabel;
    Label7: TLabel;
    Label8: TLabel;
    Bevel40: TBevel;
    Bevel38: TBevel;
    Bevel36: TBevel;
    Label33: TLabel;
    Label34: TLabel;
    Label36: TLabel;
    Bevel5: TBevel;
    Bevel8: TBevel;
    Bevel10: TBevel;
    Bevel11: TBevel;
    Label2: TLabel;
    Label3: TLabel;
    Label9: TLabel;
    Bevel12: TBevel;
    Bevel13: TBevel;
    Bevel14: TBevel;
    Label10: TLabel;
    Label11: TLabel;
    Label12: TLabel;
    IBQORCAMENTO: TIBQuery;
    IBTORCAMENTO: TIBTable;
    DSTORCAMENTO: TDataSource;
    DSQORCAMENTO: TDataSource;
    IBQGENORCAMENTO: TIBQuery;
    IBQGENORCAMENTOGEN_ID: TLargeintField;
    DSQGENORCAMENTO: TDataSource;
    IBTESTOQUE: TIBTable;
    IBTESTOQUECODIGO: TIBStringField;
    IBTESTOQUEREFERENCIA: TIBStringField;
    IBTESTOQUEDESCRICAO: TIBStringField;
    IBTESTOQUENOME: TIBStringField;
    IBTESTOQUEFORNECEDOR: TIBStringField;
    IBTESTOQUEMEDIDA: TIBStringField;
    IBTESTOQUEPRECO: TFloatField;
    IBTESTOQUEINDEXADOR: TFloatField;
    IBTESTOQUECUSTOCOMPR: TFloatField;
    IBTESTOQUECUSTOMEDIO: TFloatField;
    IBTESTOQUEQTD_COMPRA: TFloatField;
    IBTESTOQUEQTD_ATUAL: TFloatField;
    IBTESTOQUEQTD_MINIM: TFloatField;
    IBTESTOQUEQTD_INICIO: TFloatField;
    IBTESTOQUEDAT_INICIO: TDateField;
    IBTESTOQUEULT_COMPRA: TDateField;
    IBTESTOQUEULT_VENDA: TDateField;
    IBTESTOQUELIVRE1: TIBStringField;
    IBTESTOQUELIVRE2: TIBStringField;
    IBTESTOQUELIVRE3: TIBStringField;
    IBTESTOQUELIVRE4: TIBStringField;
    IBTESTOQUEPESO: TFloatField;
    IBTESTOQUELOCAL: TIBStringField;
    IBTESTOQUECF: TIBStringField;
    IBTESTOQUEIPI: TFloatField;
    IBTESTOQUECST: TIBStringField;
    IBTESTOQUEST: TIBStringField;
    IBTESTOQUECOMISSAO: TFloatField;
    IBTESTOQUEOBS: TIBStringField;
    IBTESTOQUEQTD_VEND: TFloatField;
    IBTESTOQUECUS_VEND: TFloatField;
    IBTESTOQUEVAL_VEND: TFloatField;
    IBTESTOQUELUC_VEND: TFloatField;
    IBTESTOQUEATIVO: TSmallintField;
    IBTESTOQUEMARGEMLB: TFloatField;
    IBTESTOQUEALTERADO: TSmallintField;
    IBTESTOQUESERIE: TSmallintField;
    IBTESTOQUEFOTO: TWideMemoField;
    IBTESTOQUEREGISTRO: TIBStringField;
    IBTESTOQUEPIVA: TFloatField;
    IBTESTOQUECSOSN: TIBStringField;
    IBTESTOQUEENCRYPTHASH: TIBStringField;
    IBTESTOQUEIAT: TIBStringField;
    IBTESTOQUEIPPT: TIBStringField;
    IBTESTOQUECST_IPI: TIBStringField;
    IBTESTOQUETIPO_ITEM: TIBStringField;
    IBTESTOQUECST_PIS_COFINS_ENTRADA: TIBStringField;
    IBTESTOQUEALIQ_PIS_ENTRADA: TIBBCDField;
    IBTESTOQUEALIQ_COFINS_ENTRADA: TIBBCDField;
    IBTESTOQUECST_PIS_COFINS_SAIDA: TIBStringField;
    IBTESTOQUEALIQ_PIS_SAIDA: TIBBCDField;
    IBTESTOQUEALIQ_COFINS_SAIDA: TIBBCDField;
    IBTESTOQUEONPROMO: TIBBCDField;
    IBTESTOQUEOFFPROMO: TIBBCDField;
    IBTESTOQUEPROMOINI: TDateField;
    IBTESTOQUEPROMOFIM: TDateField;
    IBTESTOQUEIIA: TFloatField;
    IBTESTOQUECFOP: TIBStringField;
    IBTESTOQUEMEDIDAE: TIBStringField;
    IBTESTOQUEFATORC: TIBBCDField;
    IBTESTOQUEVALOR_PARCELA_IMPORTADA_EXTERIO: TIBBCDField;
    IBTESTOQUECODIGO_FCI: TIBStringField;
    DSTESTOQUE: TDataSource;
    IBQGENESTOQUE: TIBQuery;
    IBQGENESTOQUEGEN_ID: TLargeintField;
    DSQGENESTOQUE: TDataSource;
    IBQESTOQUE: TIBQuery;
    IBQESTOQUECODIGO: TIBStringField;
    IBQESTOQUEREFERENCIA: TIBStringField;
    IBQESTOQUEDESCRICAO: TIBStringField;
    IBQESTOQUENOME: TIBStringField;
    IBQESTOQUEFORNECEDOR: TIBStringField;
    IBQESTOQUEMEDIDA: TIBStringField;
    IBQESTOQUEPRECO: TFloatField;
    IBQESTOQUEINDEXADOR: TFloatField;
    IBQESTOQUECUSTOCOMPR: TFloatField;
    IBQESTOQUECUSTOMEDIO: TFloatField;
    IBQESTOQUEQTD_COMPRA: TFloatField;
    IBQESTOQUEQTD_ATUAL: TFloatField;
    IBQESTOQUEQTD_MINIM: TFloatField;
    IBQESTOQUEQTD_INICIO: TFloatField;
    IBQESTOQUEDAT_INICIO: TDateField;
    IBQESTOQUEULT_COMPRA: TDateField;
    IBQESTOQUEULT_VENDA: TDateField;
    IBQESTOQUELIVRE1: TIBStringField;
    IBQESTOQUELIVRE2: TIBStringField;
    IBQESTOQUELIVRE3: TIBStringField;
    IBQESTOQUELIVRE4: TIBStringField;
    IBQESTOQUEPESO: TFloatField;
    IBQESTOQUELOCAL: TIBStringField;
    IBQESTOQUECF: TIBStringField;
    IBQESTOQUEIPI: TFloatField;
    IBQESTOQUECST: TIBStringField;
    IBQESTOQUEST: TIBStringField;
    IBQESTOQUECOMISSAO: TFloatField;
    IBQESTOQUEOBS: TIBStringField;
    IBQESTOQUEQTD_VEND: TFloatField;
    IBQESTOQUECUS_VEND: TFloatField;
    IBQESTOQUEVAL_VEND: TFloatField;
    IBQESTOQUELUC_VEND: TFloatField;
    IBQESTOQUEATIVO: TSmallintField;
    IBQESTOQUEMARGEMLB: TFloatField;
    IBQESTOQUEALTERADO: TSmallintField;
    IBQESTOQUESERIE: TSmallintField;
    IBQESTOQUEFOTO: TWideMemoField;
    IBQESTOQUEREGISTRO: TIBStringField;
    IBQESTOQUEIAT: TIBStringField;
    IBQESTOQUEIPPT: TIBStringField;
    IBQESTOQUECSOSN: TIBStringField;
    IBQESTOQUEENCRYPTHASH: TIBStringField;
    IBQESTOQUEPIVA: TFloatField;
    IBQESTOQUECFOP: TIBStringField;
    IBQESTOQUEMEDIDAE: TIBStringField;
    IBQESTOQUEFATORC: TIBBCDField;
    IBQESTOQUEVALOR_PARCELA_IMPORTADA_EXTERIO: TIBBCDField;
    IBQESTOQUECODIGO_FCI: TIBStringField;
    IBQESTOQUEIIA: TFloatField;
    IBQESTOQUEIIA_UF: TFloatField;
    IBQESTOQUEIIA_MUNI: TFloatField;
    IBQESTOQUEONPROMO: TIBBCDField;
    IBQESTOQUEOFFPROMO: TIBBCDField;
    IBQESTOQUEPROMOINI: TDateField;
    IBQESTOQUEPROMOFIM: TDateField;
    IBQESTOQUECST_IPI: TIBStringField;
    IBQESTOQUETIPO_ITEM: TIBStringField;
    IBQESTOQUECST_PIS_COFINS_ENTRADA: TIBStringField;
    IBQESTOQUEALIQ_PIS_ENTRADA: TIBBCDField;
    IBQESTOQUEALIQ_COFINS_ENTRADA: TIBBCDField;
    IBQESTOQUECST_PIS_COFINS_SAIDA: TIBStringField;
    IBQESTOQUEALIQ_PIS_SAIDA: TIBBCDField;
    IBQESTOQUEALIQ_COFINS_SAIDA: TIBBCDField;
    IBQESTOQUECEST: TIBStringField;
    IBQESTOQUECSOSN_NFCE: TIBStringField;
    IBQESTOQUECST_NFCE: TIBStringField;
    IBQESTOQUEALIQUOTA_NFCE: TIBBCDField;
    DSQESTOQUE: TDataSource;
    IBQITENS005: TIBQuery;
    IBTITENS005: TIBTable;
    IBTITENS005NUMERONF: TIBStringField;
    IBTITENS005CODIGO: TIBStringField;
    IBTITENS005DESCRICAO: TIBStringField;
    IBTITENS005ST: TIBStringField;
    IBTITENS005IPI: TFloatField;
    IBTITENS005ICM: TFloatField;
    IBTITENS005ISS: TFloatField;
    IBTITENS005MEDIDA: TIBStringField;
    IBTITENS005QUANTIDADE: TFloatField;
    IBTITENS005SINCRONIA: TFloatField;
    IBTITENS005UNITARIO: TFloatField;
    IBTITENS005TOTAL: TFloatField;
    IBTITENS005LISTA: TFloatField;
    IBTITENS005CUSTO: TFloatField;
    IBTITENS005PESO: TFloatField;
    IBTITENS005BASE: TFloatField;
    IBTITENS005BASEISS: TFloatField;
    IBTITENS005ALIQUOTA: TFloatField;
    IBTITENS005CFOP: TIBStringField;
    IBTITENS005NUMEROOS: TIBStringField;
    IBTITENS005REGISTRO: TIBStringField;
    IBTITENS005VICMS: TIBBCDField;
    IBTITENS005VBC: TIBBCDField;
    IBTITENS005VBCST: TIBBCDField;
    IBTITENS005VICMSST: TIBBCDField;
    IBTITENS005VIPI: TIBBCDField;
    IBTITENS005XPED: TIBStringField;
    IBTITENS005NITEMPED: TIBStringField;
    IBTITENS005CST_PIS_COFINS: TIBStringField;
    IBTITENS005ALIQ_PIS: TIBBCDField;
    IBTITENS005ALIQ_COFINS: TIBBCDField;
    IBTITENS005CST_IPI: TIBStringField;
    IBTITENS005CST_ICMS: TIBStringField;
    IBTITENS005ANVISA: TIntegerField;
    IBQGENITENS005: TIBQuery;
    IBQGENITENS005GEN_ID: TLargeintField;
    DSQGENITENS005: TDataSource;
    DSQITENS005: TDataSource;
    DSTITENS005: TDataSource;
    IBQPRODUTOSMAISVENDIDOS: TIBQuery;
    IBQPRODUTOSMAISVENDIDOSDESCRICAO: TIBStringField;
    IBQPRODUTOSMAISVENDIDOSQTD_ATUAL: TFloatField;
    IBQPRODUTOSMAISVENDIDOSPRODUTOTALVENDIDO: TFloatField;
    DSQPRODUTOSMAISVENDIDOS: TDataSource;
    IBQCAIXA: TIBQuery;
    IBQCAIXADATA: TDateField;
    IBQCAIXACONTA: TIBStringField;
    IBQCAIXANOME: TIBStringField;
    IBQCAIXAHISTORICO: TIBStringField;
    IBQCAIXAENTRADA: TFloatField;
    IBQCAIXASAIDA: TFloatField;
    IBQCAIXASALDO: TFloatField;
    IBQCAIXAREGISTRO: TIBStringField;
    IBTable1: TIBTable;
    DateField1: TDateField;
    IBStringField1: TIBStringField;
    IBStringField2: TIBStringField;
    IBStringField3: TIBStringField;
    FloatField1: TFloatField;
    FloatField2: TFloatField;
    FloatField3: TFloatField;
    IBStringField4: TIBStringField;
    IBQuery2: TIBQuery;
    LargeintField1: TLargeintField;
    DataSource3: TDataSource;
    DataSource4: TDataSource;
    DataSource5: TDataSource;
    IBQRECEBER: TIBQuery;
    IBQRECEBERHISTORICO: TIBStringField;
    IBQRECEBERPORTADOR: TIBStringField;
    IBQRECEBERDOCUMENTO: TIBStringField;
    IBQRECEBERNOME: TIBStringField;
    IBQRECEBEREMISSAO: TDateField;
    IBQRECEBERVENCIMENTO: TDateField;
    IBQRECEBERVALOR_DUPL: TFloatField;
    IBQRECEBERRECEBIMENT: TDateField;
    IBQRECEBERVALOR_RECE: TFloatField;
    IBQRECEBERVALOR_JURO: TFloatField;
    IBQRECEBERATIVO: TSmallintField;
    IBQRECEBERCONTA: TIBStringField;
    IBQRECEBERNOSSONUM: TIBStringField;
    IBQRECEBERCODEBAR: TIBStringField;
    IBQRECEBERNUMERONF: TIBStringField;
    IBQRECEBERREGISTRO: TIBStringField;
    IBTRECEBER: TIBTable;
    IBTRECEBERHISTORICO: TIBStringField;
    IBTRECEBERPORTADOR: TIBStringField;
    IBTRECEBERDOCUMENTO: TIBStringField;
    IBTRECEBERNOME: TIBStringField;
    IBTRECEBEREMISSAO: TDateField;
    IBTRECEBERVENCIMENTO: TDateField;
    IBTRECEBERVALOR_DUPL: TFloatField;
    IBTRECEBERRECEBIMENT: TDateField;
    IBTRECEBERVALOR_RECE: TFloatField;
    IBTRECEBERVALOR_JURO: TFloatField;
    IBTRECEBERATIVO: TSmallintField;
    IBTRECEBERCONTA: TIBStringField;
    IBTRECEBERNOSSONUM: TIBStringField;
    IBTRECEBERCODEBAR: TIBStringField;
    IBTRECEBERNUMERONF: TIBStringField;
    IBTRECEBERREGISTRO: TIBStringField;
    IBQGENRECEBER: TIBQuery;
    LargeintField2: TLargeintField;
    DSQGENRECEBER: TDataSource;
    DSQRECEBER: TDataSource;
    DSTRECEBER: TDataSource;
    QuickRep2: TQuickRep;
    QRBand3: TQRBand;
    QRLabel65: TQRLabel;
    QRLabel66: TQRLabel;
    QRLabel67: TQRLabel;
    QRLabel79: TQRLabel;
    QRLabel80: TQRLabel;
    QRShape14: TQRShape;
    QRLabel61: TQRLabel;
    QRShape11: TQRShape;
    QRSysData2: TQRSysData;
    QRSysData3: TQRSysData;
    QRShape13: TQRShape;
    QRLabel58: TQRLabel;
    QRSubDetail2: TQRSubDetail;
    QRDBText34: TQRDBText;
    QRDBText35: TQRDBText;
    QRDBText36: TQRDBText;
    QRBand4: TQRBand;
    QRShape12: TQRShape;
    QRLabel69: TQRLabel;
    QRShape18: TQRShape;
    QRLabel63: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel27: TQRLabel;
    QRBand5: TQRBand;
    QRShape15: TQRShape;
    QuickRep3: TQuickRep;
    QRBand6: TQRBand;
    QRLabel64: TQRLabel;
    QRLabel68: TQRLabel;
    QRLabel71: TQRLabel;
    QRLabel72: TQRLabel;
    QRLabel73: TQRLabel;
    QRShape16: TQRShape;
    QRLabel74: TQRLabel;
    QRShape17: TQRShape;
    QRLabel76: TQRLabel;
    QRLabel77: TQRLabel;
    QRSysData5: TQRSysData;
    QRSysData6: TQRSysData;
    QRShape19: TQRShape;
    QRSubDetail3: TQRSubDetail;
    QRDBText21: TQRDBText;
    QRDBText37: TQRDBText;
    QRDBText40: TQRDBText;
    QRBand8: TQRBand;
    QRShape22: TQRShape;
    QRSysData7: TQRSysData;
    QuickRep100: TQuickRep;
    QRBand1: TQRBand;
    QRDBText11: TQRDBText;
    Bevel16: TBevel;
    Label13: TLabel;
    Label14: TLabel;
    IBQClifor: TIBQuery;
    IBQCliforNOME: TIBStringField;
    IBQCliforCONTATO: TIBStringField;
    IBQCliforIE: TIBStringField;
    IBQCliforCGC: TIBStringField;
    IBQCliforENDERE: TIBStringField;
    IBQCliforCOMPLE: TIBStringField;
    IBQCliforCIDADE: TIBStringField;
    IBQCliforESTADO: TIBStringField;
    IBQCliforCEP: TIBStringField;
    IBQCliforFONE: TIBStringField;
    IBQCliforFAX: TIBStringField;
    IBQCliforEMAIL: TIBStringField;
    IBQCliforOBS: TIBStringField;
    IBQCliforCELULAR: TIBStringField;
    IBQCliforCREDITO: TFloatField;
    IBQCliforCONVENIO: TIBStringField;
    IBQCliforIDENTIFICADOR1: TIBStringField;
    IBQCliforIDENTIFICADOR2: TIBStringField;
    IBQCliforIDENTIFICADOR3: TIBStringField;
    IBQCliforIDENTIFICADOR4: TIBStringField;
    IBQCliforIDENTIFICADOR5: TIBStringField;
    IBQCliforDATANAS: TDateField;
    IBQCliforCADASTRO: TDateField;
    IBQCliforULTIMACO: TDateField;
    IBQCliforPROXDATA: TDateField;
    IBQCliforCUSTO: TFloatField;
    IBQCliforCOMPRA: TFloatField;
    IBQCliforATIVO: TSmallintField;
    IBQCliforMOSTRAR: TIBStringField;
    IBQCliforCLIFOR: TIBStringField;
    IBQCliforCONTATOS: TWideMemoField;
    IBQCliforREGISTRO: TIBStringField;
    IBQCliforFOTO: TBlobField;
    DSQClifor: TDataSource;
    IBQGenClifor: TIBQuery;
    IBQGenCliforGEN_ID: TLargeintField;
    DSQGENClifor: TDataSource;
    Bevel3: TBevel;
    Label1: TLabel;
    IBQENTREGADOR: TIBQuery;
    DSQENTREGADOR: TDataSource;
    IBQENTREGADORNOME: TIBStringField;
    IBQENTREGADORPLACA: TIBStringField;
    IBQENTREGADORENDERECO: TIBStringField;
    IBQENTREGADORMUNICIPIO: TIBStringField;
    IBQENTREGADORESTADO: TIBStringField;
    IBQENTREGADORCGC: TIBStringField;
    IBQENTREGADORIE: TIBStringField;
    IBQENTREGADORFONE: TIBStringField;
    IBQENTREGADORUF: TIBStringField;
    IBQENTREGADOREMAIL: TIBStringField;
    IBQENTREGADORREGISTRO: TIBStringField;
    IBQENTREGADORANTT: TIBStringField;
    IBQESTOQUEPRECOMINIMOPERCENTUAL: TFloatField;
    IBQESTOQUEPRECOMINIMOREAL: TFloatField;
    IBQESTOQUEPRECOMAXIMOPERCENTUAL: TFloatField;
    IBQESTOQUEPRECOMAXIMOREAL: TFloatField;
    IBQITENS005NUMERONF: TIBStringField;
    IBQITENS005CODIGO: TIBStringField;
    IBQITENS005DESCRICAO: TIBStringField;
    IBQITENS005ST: TIBStringField;
    IBQITENS005IPI: TFloatField;
    IBQITENS005ICM: TFloatField;
    IBQITENS005ISS: TFloatField;
    IBQITENS005MEDIDA: TIBStringField;
    IBQITENS005QUANTIDADE: TFloatField;
    IBQITENS005SINCRONIA: TFloatField;
    IBQITENS005UNITARIO: TFloatField;
    IBQITENS005TOTAL: TFloatField;
    IBQITENS005LISTA: TFloatField;
    IBQITENS005CUSTO: TFloatField;
    IBQITENS005PESO: TFloatField;
    IBQITENS005BASE: TFloatField;
    IBQITENS005BASEISS: TFloatField;
    IBQITENS005ALIQUOTA: TFloatField;
    IBQITENS005CFOP: TIBStringField;
    IBQITENS005NUMEROOS: TIBStringField;
    IBQITENS005REGISTRO: TIBStringField;
    IBQITENS005VICMS: TIBBCDField;
    IBQITENS005VBC: TIBBCDField;
    IBQITENS005VBCST: TIBBCDField;
    IBQITENS005VICMSST: TIBBCDField;
    IBQITENS005VIPI: TIBBCDField;
    IBQITENS005XPED: TIBStringField;
    IBQITENS005NITEMPED: TIBStringField;
    IBQITENS005CST_PIS_COFINS: TIBStringField;
    IBQITENS005ALIQ_PIS: TIBBCDField;
    IBQITENS005ALIQ_COFINS: TIBBCDField;
    IBQITENS005CST_IPI: TIBStringField;
    IBQITENS005CST_ICMS: TIBStringField;
    IBQITENS005ANVISA: TIntegerField;
    IBQITENS005OBSERVACAO: TIBStringField;
    QRLabel31: TQRLabel;
    QRLabel36: TQRLabel;
    QRDBText15: TQRDBText;
    QRDBText17: TQRDBText;
    IBTORCAMENTONUMERONF: TIBStringField;
    IBTORCAMENTOMODELO: TIBStringField;
    IBTORCAMENTOVENDEDOR: TIBStringField;
    IBTORCAMENTOCLIENTE: TIBStringField;
    IBTORCAMENTOOPERACAO: TIBStringField;
    IBTORCAMENTOEMISSAO: TDateField;
    IBTORCAMENTOFRETE: TFloatField;
    IBTORCAMENTOSEGURO: TFloatField;
    IBTORCAMENTODESPESAS: TFloatField;
    IBTORCAMENTODESCONTO: TFloatField;
    IBTORCAMENTOVOLUMES: TFloatField;
    IBTORCAMENTOESPECIE: TIBStringField;
    IBTORCAMENTOMARCA: TIBStringField;
    IBTORCAMENTOTRANSPORTA: TIBStringField;
    IBTORCAMENTOFRETE12: TIBStringField;
    IBTORCAMENTOSAIDAH: TIBStringField;
    IBTORCAMENTOSAIDAD: TDateField;
    IBTORCAMENTODUPLICATAS: TFloatField;
    IBTORCAMENTOBASEICM: TFloatField;
    IBTORCAMENTOBASEISS: TFloatField;
    IBTORCAMENTOICMS: TFloatField;
    IBTORCAMENTOICMSSUBSTI: TFloatField;
    IBTORCAMENTOBASESUBSTI: TFloatField;
    IBTORCAMENTOALIQUOTA: TFloatField;
    IBTORCAMENTOISS: TFloatField;
    IBTORCAMENTOIPI: TFloatField;
    IBTORCAMENTOTOTAL: TFloatField;
    IBTORCAMENTOMERCADORIA: TFloatField;
    IBTORCAMENTOEMITIDA: TIBStringField;
    IBTORCAMENTOSERVICOS: TFloatField;
    IBTORCAMENTOPESOBRUTO: TFloatField;
    IBTORCAMENTOPESOLIQUI: TFloatField;
    IBTORCAMENTOREGISTRO: TIBStringField;
    IBTORCAMENTONSUH: TIBStringField;
    IBTORCAMENTONSU: TIBStringField;
    IBTORCAMENTONSUD: TDateField;
    IBTORCAMENTOIDENTIFICADOR1: TIBStringField;
    IBTORCAMENTOLOKED: TIBStringField;
    IBTORCAMENTONFEPROTOCOLO: TIBStringField;
    IBTORCAMENTOSTATUS: TIBStringField;
    IBTORCAMENTONFEID: TIBStringField;
    IBTORCAMENTONFERECIBO: TIBStringField;
    IBTORCAMENTONFEXML: TWideMemoField;
    IBTORCAMENTORECIBOXML: TWideMemoField;
    IBTORCAMENTOCOMPLEMENTO: TWideMemoField;
    IBTORCAMENTODATA_CANCEL: TDateField;
    IBTORCAMENTOHORA_CANCEL: TIBStringField;
    IBTORCAMENTOCOD_SIT: TIBStringField;
    IBTORCAMENTOPLACA: TIBStringField;
    IBTORCAMENTOANVISA: TIntegerField;
    IBTORCAMENTONVOL: TIBStringField;
    IBTORCAMENTOICCE: TIntegerField;
    IBTORCAMENTOCCEXML: TWideMemoField;
    IBTORCAMENTOEMAIL: TIBStringField;
    IBTORCAMENTOTRANSPORTADORA: TIBStringField;
    IBTORCAMENTOPRAZODEPAGAMENTO: TIBStringField;
    IBTORCAMENTOFORMADEPAGAMENTO: TIBStringField;
    IBTORCAMENTOB1: TFloatField;
    IBTORCAMENTOB2: TFloatField;
    IBTORCAMENTOB3: TFloatField;
    IBTORCAMENTOB4: TFloatField;
    IBTORCAMENTOB5: TFloatField;
    IBTORCAMENTOB6: TFloatField;
    IBTORCAMENTOB7: TFloatField;
    IBTORCAMENTOB8: TFloatField;
    IBTORCAMENTOB9: TFloatField;
    IBTORCAMENTOB10: TFloatField;
    IBTORCAMENTOB11: TFloatField;
    IBTORCAMENTOB12: TFloatField;
    IBTORCAMENTOP1: TDateField;
    IBTORCAMENTOP2: TDateField;
    IBTORCAMENTOP3: TDateField;
    IBTORCAMENTOP4: TDateField;
    IBTORCAMENTOP5: TDateField;
    IBTORCAMENTOP6: TDateField;
    IBTORCAMENTOP7: TDateField;
    IBTORCAMENTOP8: TDateField;
    IBTORCAMENTOP9: TDateField;
    IBTORCAMENTOP10: TDateField;
    IBTORCAMENTOP11: TDateField;
    IBTORCAMENTOP12: TDateField;
    IBTORCAMENTODESCRICAO1: TIBStringField;
    IBTORCAMENTODESCRICAO2: TIBStringField;
    IBTORCAMENTODESCRICAO3: TIBStringField;
    IBTORCAMENTODATA: TDateField;
    IBTORCAMENTOENTREGADOR: TIBStringField;
    IBTORCAMENTOTEMPODEENTREGA: TIBStringField;
    IBTORCAMENTOFORMA: TIBStringField;
    IBTORCAMENTOTROCO: TIBStringField;
    IBTORCAMENTOOBSERVACAO: TIBStringField;
    IBTORCAMENTOMESA: TIntegerField;
    IBTORCAMENTOCB1: TIBStringField;
    IBTORCAMENTOCB2: TIBStringField;
    IBTORCAMENTOCB3: TIBStringField;
    IBTORCAMENTOCB4: TIBStringField;
    IBTORCAMENTOCB5: TIBStringField;
    IBTORCAMENTOCB6: TIBStringField;
    IBTORCAMENTOCB7: TIBStringField;
    IBTORCAMENTOCB8: TIBStringField;
    IBTORCAMENTOCB9: TIBStringField;
    IBTORCAMENTOCB10: TIBStringField;
    IBTORCAMENTOCB11: TIBStringField;
    IBTORCAMENTOCB12: TIBStringField;
    IBTORCAMENTOCB13: TIBStringField;
    IBTORCAMENTOCB14: TIBStringField;
    IBTORCAMENTOCB15: TIBStringField;
    IBTORCAMENTOCB16: TIBStringField;
    IBTORCAMENTOCB17: TIBStringField;
    IBTORCAMENTOCB18: TIBStringField;
    IBTORCAMENTOCB19: TIBStringField;
    IBTORCAMENTOCB20: TIBStringField;
    IBTORCAMENTOCB21: TIBStringField;
    IBTORCAMENTOCB22: TIBStringField;
    IBTORCAMENTOCB23: TIBStringField;
    IBTORCAMENTOCB24: TIBStringField;
    IBTORCAMENTOCB25: TIBStringField;
    IBTORCAMENTOCB26: TIBStringField;
    IBTORCAMENTOCB27: TIBStringField;
    IBTORCAMENTOCB28: TIBStringField;
    IBTORCAMENTOCB29: TIBStringField;
    IBTORCAMENTOCB30: TIBStringField;
    IBTORCAMENTOCB31: TIBStringField;
    IBTORCAMENTOCB32: TIBStringField;
    IBTORCAMENTOCB33: TIBStringField;
    IBTORCAMENTOCB34: TIBStringField;
    IBTORCAMENTOCB35: TIBStringField;
    IBTORCAMENTOCB36: TIBStringField;
    IBTORCAMENTOCB37: TIBStringField;
    IBTORCAMENTOCB38: TIBStringField;
    IBTORCAMENTOCB39: TIBStringField;
    IBTORCAMENTOCB40: TIBStringField;
    IBTORCAMENTOCB41: TIBStringField;
    IBTORCAMENTOCB42: TIBStringField;
    IBTORCAMENTOCB43: TIBStringField;
    IBTORCAMENTOCB44: TIBStringField;
    IBTORCAMENTOCB45: TIBStringField;
    IBTORCAMENTOCB46: TIBStringField;
    IBTORCAMENTOCB47: TIBStringField;
    IBTORCAMENTOCB48: TIBStringField;
    IBTORCAMENTOCB49: TIBStringField;
    IBTORCAMENTOCB50: TIBStringField;
    IBTORCAMENTOCB51: TIBStringField;
    IBQORCAMENTONUMERONF: TIBStringField;
    IBQORCAMENTOMODELO: TIBStringField;
    IBQORCAMENTOVENDEDOR: TIBStringField;
    IBQORCAMENTOCLIENTE: TIBStringField;
    IBQORCAMENTOOPERACAO: TIBStringField;
    IBQORCAMENTOEMISSAO: TDateField;
    IBQORCAMENTOFRETE: TFloatField;
    IBQORCAMENTOSEGURO: TFloatField;
    IBQORCAMENTODESPESAS: TFloatField;
    IBQORCAMENTODESCONTO: TFloatField;
    IBQORCAMENTOVOLUMES: TFloatField;
    IBQORCAMENTOESPECIE: TIBStringField;
    IBQORCAMENTOMARCA: TIBStringField;
    IBQORCAMENTOTRANSPORTA: TIBStringField;
    IBQORCAMENTOFRETE12: TIBStringField;
    IBQORCAMENTOSAIDAH: TIBStringField;
    IBQORCAMENTOSAIDAD: TDateField;
    IBQORCAMENTODUPLICATAS: TFloatField;
    IBQORCAMENTOBASEICM: TFloatField;
    IBQORCAMENTOBASEISS: TFloatField;
    IBQORCAMENTOICMS: TFloatField;
    IBQORCAMENTOICMSSUBSTI: TFloatField;
    IBQORCAMENTOBASESUBSTI: TFloatField;
    IBQORCAMENTOALIQUOTA: TFloatField;
    IBQORCAMENTOISS: TFloatField;
    IBQORCAMENTOIPI: TFloatField;
    IBQORCAMENTOTOTAL: TFloatField;
    IBQORCAMENTOMERCADORIA: TFloatField;
    IBQORCAMENTOEMITIDA: TIBStringField;
    IBQORCAMENTOSERVICOS: TFloatField;
    IBQORCAMENTOPESOBRUTO: TFloatField;
    IBQORCAMENTOPESOLIQUI: TFloatField;
    IBQORCAMENTOREGISTRO: TIBStringField;
    IBQORCAMENTONSUH: TIBStringField;
    IBQORCAMENTONSU: TIBStringField;
    IBQORCAMENTONSUD: TDateField;
    IBQORCAMENTOIDENTIFICADOR1: TIBStringField;
    IBQORCAMENTOLOKED: TIBStringField;
    IBQORCAMENTONFEPROTOCOLO: TIBStringField;
    IBQORCAMENTOSTATUS: TIBStringField;
    IBQORCAMENTONFEID: TIBStringField;
    IBQORCAMENTONFERECIBO: TIBStringField;
    IBQORCAMENTONFEXML: TWideMemoField;
    IBQORCAMENTORECIBOXML: TWideMemoField;
    IBQORCAMENTOCOMPLEMENTO: TWideMemoField;
    IBQORCAMENTODATA_CANCEL: TDateField;
    IBQORCAMENTOHORA_CANCEL: TIBStringField;
    IBQORCAMENTOCOD_SIT: TIBStringField;
    IBQORCAMENTOPLACA: TIBStringField;
    IBQORCAMENTOANVISA: TIntegerField;
    IBQORCAMENTONVOL: TIBStringField;
    IBQORCAMENTOICCE: TIntegerField;
    IBQORCAMENTOCCEXML: TWideMemoField;
    IBQORCAMENTOEMAIL: TIBStringField;
    IBQORCAMENTOTRANSPORTADORA: TIBStringField;
    IBQORCAMENTOPRAZODEPAGAMENTO: TIBStringField;
    IBQORCAMENTOFORMADEPAGAMENTO: TIBStringField;
    IBQORCAMENTOB1: TFloatField;
    IBQORCAMENTOB2: TFloatField;
    IBQORCAMENTOB3: TFloatField;
    IBQORCAMENTOB4: TFloatField;
    IBQORCAMENTOB5: TFloatField;
    IBQORCAMENTOB6: TFloatField;
    IBQORCAMENTOB7: TFloatField;
    IBQORCAMENTOB8: TFloatField;
    IBQORCAMENTOB9: TFloatField;
    IBQORCAMENTOB10: TFloatField;
    IBQORCAMENTOB11: TFloatField;
    IBQORCAMENTOB12: TFloatField;
    IBQORCAMENTOP1: TDateField;
    IBQORCAMENTOP2: TDateField;
    IBQORCAMENTOP3: TDateField;
    IBQORCAMENTOP4: TDateField;
    IBQORCAMENTOP5: TDateField;
    IBQORCAMENTOP6: TDateField;
    IBQORCAMENTOP7: TDateField;
    IBQORCAMENTOP8: TDateField;
    IBQORCAMENTOP9: TDateField;
    IBQORCAMENTOP10: TDateField;
    IBQORCAMENTOP11: TDateField;
    IBQORCAMENTOP12: TDateField;
    IBQORCAMENTODESCRICAO1: TIBStringField;
    IBQORCAMENTODESCRICAO2: TIBStringField;
    IBQORCAMENTODESCRICAO3: TIBStringField;
    IBQORCAMENTODATA: TDateField;
    IBQORCAMENTOENTREGADOR: TIBStringField;
    IBQORCAMENTOTEMPODEENTREGA: TIBStringField;
    IBQORCAMENTOFORMA: TIBStringField;
    IBQORCAMENTOTROCO: TIBStringField;
    IBQORCAMENTOOBSERVACAO: TIBStringField;
    IBQORCAMENTOMESA: TIntegerField;
    IBQORCAMENTOCB1: TIBStringField;
    IBQORCAMENTOCB2: TIBStringField;
    IBQORCAMENTOCB3: TIBStringField;
    IBQORCAMENTOCB4: TIBStringField;
    IBQORCAMENTOCB5: TIBStringField;
    IBQORCAMENTOCB6: TIBStringField;
    IBQORCAMENTOCB7: TIBStringField;
    IBQORCAMENTOCB8: TIBStringField;
    IBQORCAMENTOCB9: TIBStringField;
    IBQORCAMENTOCB10: TIBStringField;
    IBQORCAMENTOCB11: TIBStringField;
    IBQORCAMENTOCB12: TIBStringField;
    IBQORCAMENTOCB13: TIBStringField;
    IBQORCAMENTOCB14: TIBStringField;
    IBQORCAMENTOCB15: TIBStringField;
    IBQORCAMENTOCB16: TIBStringField;
    IBQORCAMENTOCB17: TIBStringField;
    IBQORCAMENTOCB18: TIBStringField;
    IBQORCAMENTOCB19: TIBStringField;
    IBQORCAMENTOCB20: TIBStringField;
    IBQORCAMENTOCB21: TIBStringField;
    IBQORCAMENTOCB22: TIBStringField;
    IBQORCAMENTOCB23: TIBStringField;
    IBQORCAMENTOCB24: TIBStringField;
    IBQORCAMENTOCB25: TIBStringField;
    IBQORCAMENTOCB26: TIBStringField;
    IBQORCAMENTOCB27: TIBStringField;
    IBQORCAMENTOCB28: TIBStringField;
    IBQORCAMENTOCB29: TIBStringField;
    IBQORCAMENTOCB30: TIBStringField;
    IBQORCAMENTOCB31: TIBStringField;
    IBQORCAMENTOCB32: TIBStringField;
    IBQORCAMENTOCB33: TIBStringField;
    IBQORCAMENTOCB34: TIBStringField;
    IBQORCAMENTOCB35: TIBStringField;
    IBQORCAMENTOCB36: TIBStringField;
    IBQORCAMENTOCB37: TIBStringField;
    IBQORCAMENTOCB38: TIBStringField;
    IBQORCAMENTOCB39: TIBStringField;
    IBQORCAMENTOCB40: TIBStringField;
    IBQORCAMENTOCB41: TIBStringField;
    IBQORCAMENTOCB42: TIBStringField;
    IBQORCAMENTOCB43: TIBStringField;
    IBQORCAMENTOCB44: TIBStringField;
    IBQORCAMENTOCB45: TIBStringField;
    IBQORCAMENTOCB46: TIBStringField;
    IBQORCAMENTOCB47: TIBStringField;
    IBQORCAMENTOCB48: TIBStringField;
    IBQORCAMENTOCB49: TIBStringField;
    IBQORCAMENTOCB50: TIBStringField;
    IBQORCAMENTOCB51: TIBStringField;
    QRCheckBox50: TQRPCheckBox;
    QRLabel1: TQRLabel;
    QRCheckBox51: TQRPCheckBox;
    QRLabel3: TQRLabel;
    QRDBText4: TQRDBText;
    QRLabel4: TQRLabel;
    QRCheckBox1: TQRPCheckBox;
    QRLabel2: TQRLabel;
    QRCheckBox2: TQRPCheckBox;
    QRCheckBox3: TQRPCheckBox;
    QRCheckBox4: TQRPCheckBox;
    QRCheckBox5: TQRPCheckBox;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRCheckBox6: TQRPCheckBox;
    QRLabel9: TQRLabel;
    QRCheckBox7: TQRPCheckBox;
    QRLabel10: TQRLabel;
    QRCheckBox8: TQRPCheckBox;
    QRLabel11: TQRLabel;
    QRCheckBox9: TQRPCheckBox;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRLabel15: TQRLabel;
    QRCheckBox17: TQRPCheckBox;
    QRLabel16: TQRLabel;
    QRCheckBox20: TQRPCheckBox;
    QRLabel17: TQRLabel;
    QRCheckBox21: TQRPCheckBox;
    QRLabel18: TQRLabel;
    QRCheckBox16: TQRPCheckBox;
    QRLabel19: TQRLabel;
    QRCheckBox19: TQRPCheckBox;
    QRLabel20: TQRLabel;
    QRCheckBox18: TQRPCheckBox;
    QRLabel21: TQRLabel;
    QRCheckBox12: TQRPCheckBox;
    QRLabel22: TQRLabel;
    QRCheckBox11: TQRPCheckBox;
    QRLabel28: TQRLabel;
    QRCheckBox10: TQRPCheckBox;
    QRLabel29: TQRLabel;
    QRCheckBox15: TQRPCheckBox;
    QRLabel30: TQRLabel;
    QRCheckBox14: TQRPCheckBox;
    QRLabel32: TQRLabel;
    QRCheckBox13: TQRPCheckBox;
    QRLabel33: TQRLabel;
    QRCheckBox22: TQRPCheckBox;
    QRLabel34: TQRLabel;
    QRCheckBox40: TQRPCheckBox;
    QRLabel35: TQRLabel;
    QRCheckBox39: TQRPCheckBox;
    QRLabel37: TQRLabel;
    QRCheckBox38: TQRPCheckBox;
    QRLabel38: TQRLabel;
    QRLabel39: TQRLabel;
    QRCheckBox42: TQRPCheckBox;
    QRLabel40: TQRLabel;
    QRCheckBox41: TQRPCheckBox;
    QRCheckBox30: TQRPCheckBox;
    QRLabel41: TQRLabel;
    QRCheckBox33: TQRPCheckBox;
    QRLabel42: TQRLabel;
    QRCheckBox34: TQRPCheckBox;
    QRLabel43: TQRLabel;
    QRCheckBox29: TQRPCheckBox;
    QRLabel44: TQRLabel;
    QRCheckBox32: TQRPCheckBox;
    QRLabel45: TQRLabel;
    QRCheckBox31: TQRPCheckBox;
    QRLabel46: TQRLabel;
    QRCheckBox25: TQRPCheckBox;
    QRLabel47: TQRLabel;
    QRCheckBox24: TQRPCheckBox;
    QRLabel48: TQRLabel;
    QRCheckBox23: TQRPCheckBox;
    QRLabel49: TQRLabel;
    QRCheckBox28: TQRPCheckBox;
    QRLabel50: TQRLabel;
    QRCheckBox27: TQRPCheckBox;
    QRLabel51: TQRLabel;
    QRCheckBox26: TQRPCheckBox;
    QRLabel52: TQRLabel;
    QRCheckBox35: TQRPCheckBox;
    QRLabel53: TQRLabel;
    QRCheckBox36: TQRPCheckBox;
    QRLabel54: TQRLabel;
    QRCheckBox37: TQRPCheckBox;
    QRLabel55: TQRLabel;
    QRLabel56: TQRLabel;
    QRLabel59: TQRLabel;
    QRCheckBox45: TQRPCheckBox;
    QRLabel60: TQRLabel;
    QRCheckBox44: TQRPCheckBox;
    QRLabel62: TQRLabel;
    QRCheckBox43: TQRPCheckBox;
    QRLabel70: TQRLabel;
    QRLabel78: TQRLabel;
    QRCheckBox47: TQRPCheckBox;
    QRLabel81: TQRLabel;
    QRCheckBox46: TQRPCheckBox;
    QRLabel82: TQRLabel;
    QRCheckBox49: TQRPCheckBox;
    QRLabel83: TQRLabel;
    QRCheckBox48: TQRPCheckBox;
    QRLabel84: TQRLabel;
    QRLabel85: TQRLabel;
    QRLabel86: TQRLabel;
    QRLabel87: TQRLabel;
    QRLabel88: TQRLabel;
    QuickRep1: TQuickRep;
    QRBand2: TQRBand;
    QRLabel90: TQRLabel;
    QRLabel93: TQRLabel;
    QRLabel96: TQRLabel;
    QRLabel97: TQRLabel;
    QRDBText1: TQRDBText;
    QRSysData1: TQRSysData;
    QRLabel98: TQRLabel;
    QRLabel104: TQRLabel;
    QRLabel106: TQRLabel;
    QRLabel107: TQRLabel;
    QRDBText3: TQRDBText;
    QRDBText19: TQRDBText;
    QRDBText20: TQRDBText;
    QRLabel109: TQRLabel;
    QRDBText5: TQRDBText;
    QRLabel110: TQRLabel;
    QRDBText23: TQRDBText;
    QRSubDetail1: TQRSubDetail;
    QRDBText6: TQRDBText;
    QRLabel112: TQRLabel;
    QRDBText7: TQRDBText;
    QRDBText9: TQRDBText;
    QRBand7: TQRBand;
    QRLabel114: TQRLabel;
    QRLabel116: TQRLabel;
    QRLabel117: TQRLabel;
    QRLabel123: TQRLabel;
    QRLabel124: TQRLabel;
    QRLabel126: TQRLabel;
    QRLabel127: TQRLabel;
    QRDBText28: TQRDBText;
    QRLabel128: TQRLabel;
    QRLabel129: TQRLabel;
    QRLabel130: TQRLabel;
    QRLabel131: TQRLabel;
    QRDBText22: TQRDBText;
    IBTORCAMENTOCB52: TIBStringField;
    IBTORCAMENTOCB53: TIBStringField;
    IBTORCAMENTOCB54: TIBStringField;
    IBTORCAMENTOCB55: TIBStringField;
    IBQORCAMENTOCB52: TIBStringField;
    IBQORCAMENTOCB53: TIBStringField;
    IBQORCAMENTOCB54: TIBStringField;
    IBQORCAMENTOCB55: TIBStringField;
    IBTORCAMENTOCB56: TIBStringField;
    IBTORCAMENTOCB57: TIBStringField;
    IBQORCAMENTOCB56: TIBStringField;
    IBQORCAMENTOCB57: TIBStringField;
    QuickRep4: TQuickRep;
    QRBand9: TQRBand;
    QRLabel94: TQRLabel;
    QRLabel95: TQRLabel;
    QRLabel99: TQRLabel;
    QRLabel100: TQRLabel;
    QRLabel101: TQRLabel;
    QRDBText29: TQRDBText;
    QRSysData8: TQRSysData;
    QRLabel102: TQRLabel;
    QRLabel103: TQRLabel;
    QRDBText30: TQRDBText;
    QRDBText31: TQRDBText;
    QRLabel108: TQRLabel;
    QRLabel132: TQRLabel;
    QRLabel133: TQRLabel;
    QRDBText32: TQRDBText;
    QRDBText33: TQRDBText;
    QRDBText38: TQRDBText;
    QRDBText41: TQRDBText;
    QRLabel134: TQRLabel;
    QRDBText42: TQRDBText;
    QRLabel135: TQRLabel;
    QRDBText43: TQRDBText;
    QRLabel136: TQRLabel;
    QRDBText44: TQRDBText;
    QRPCheckBox3: TQRPCheckBox;
    QRLabel137: TQRLabel;
    QRPCheckBox4: TQRPCheckBox;
    QRLabel138: TQRLabel;
    QRDBText45: TQRDBText;
    QRDBText46: TQRDBText;
    QRSubDetail4: TQRSubDetail;
    QRDBText47: TQRDBText;
    QRLabel139: TQRLabel;
    QRDBText48: TQRDBText;
    QRDBText49: TQRDBText;
    QRDBText50: TQRDBText;
    QRBand10: TQRBand;
    QRLabel140: TQRLabel;
    QRLabel141: TQRLabel;
    QRLabel142: TQRLabel;
    QRLabel143: TQRLabel;
    QRLabel144: TQRLabel;
    QRLabel145: TQRLabel;
    QRDBText51: TQRDBText;
    QRLabel146: TQRLabel;
    QRDBText52: TQRDBText;
    QRLabel147: TQRLabel;
    QRDBText53: TQRDBText;
    QRLabel148: TQRLabel;
    QRLabel149: TQRLabel;
    QRLabel150: TQRLabel;
    QRLabel151: TQRLabel;
    QRDBText54: TQRDBText;
    QRLabel152: TQRLabel;
    QRLabel153: TQRLabel;
    QRLabel154: TQRLabel;
    QRDBText55: TQRDBText;
    QRLabel155: TQRLabel;
    QRLabel156: TQRLabel;
    QRLabel157: TQRLabel;
    QRLabel158: TQRLabel;
    QRPCheckBox1: TQRPCheckBox;
    QRLabel89: TQRLabel;
    QRPCheckBox2: TQRPCheckBox;
    QRLabel91: TQRLabel;
    QRDBText12: TQRDBText;
    QRLabel159: TQRLabel;
    QRLabel160: TQRLabel;
    QRLabel105: TQRLabel;
    QRDBText18: TQRDBText;
    QRLabel111: TQRLabel;
    QRDBText2: TQRDBText;
    QRLabel161: TQRLabel;
    QRLabel162: TQRLabel;
    QRLabel163: TQRLabel;
    QRLabel164: TQRLabel;
    QRLabel165: TQRLabel;
    QuickRep5: TQuickRep;
    QRBand11: TQRBand;
    QRLabel166: TQRLabel;
    QRLabel167: TQRLabel;
    QRLabel168: TQRLabel;
    QRLabel169: TQRLabel;
    QRLabel170: TQRLabel;
    QRDBText8: TQRDBText;
    QRSysData9: TQRSysData;
    QRLabel171: TQRLabel;
    QRLabel172: TQRLabel;
    QRLabel173: TQRLabel;
    QRLabel174: TQRLabel;
    QRDBText16: TQRDBText;
    QRDBText24: TQRDBText;
    QRDBText56: TQRDBText;
    QRLabel175: TQRLabel;
    QRDBText57: TQRDBText;
    QRLabel176: TQRLabel;
    QRDBText58: TQRDBText;
    QRDBText59: TQRDBText;
    QRPCheckBox5: TQRPCheckBox;
    QRLabel177: TQRLabel;
    QRPCheckBox6: TQRPCheckBox;
    QRLabel178: TQRLabel;
    QRDBText60: TQRDBText;
    QRLabel179: TQRLabel;
    QRLabel180: TQRLabel;
    QRLabel181: TQRLabel;
    QRDBText61: TQRDBText;
    QRLabel182: TQRLabel;
    QRDBText62: TQRDBText;
    QRSubDetail5: TQRSubDetail;
    QRDBText63: TQRDBText;
    QRLabel183: TQRLabel;
    QRDBText64: TQRDBText;
    QRDBText65: TQRDBText;
    QRBand12: TQRBand;
    QRLabel184: TQRLabel;
    QRLabel185: TQRLabel;
    QRLabel186: TQRLabel;
    QRLabel187: TQRLabel;
    QRLabel188: TQRLabel;
    QRLabel189: TQRLabel;
    QRDBText66: TQRDBText;
    QRLabel190: TQRLabel;
    QRDBText67: TQRDBText;
    QRLabel191: TQRLabel;
    QRDBText68: TQRDBText;
    QRLabel192: TQRLabel;
    QRLabel193: TQRLabel;
    QRLabel194: TQRLabel;
    QRLabel195: TQRLabel;
    QRDBText69: TQRDBText;
    QRLabel196: TQRLabel;
    QRLabel197: TQRLabel;
    QRLabel198: TQRLabel;
    QRDBText70: TQRDBText;
    QRLabel199: TQRLabel;
    QRLabel200: TQRLabel;
    QRLabel201: TQRLabel;
    QRLabel202: TQRLabel;
    QRLabel203: TQRLabel;
    QRLabel204: TQRLabel;
    QRLabel205: TQRLabel;
    QRLabel206: TQRLabel;
    QRLabel207: TQRLabel;
    QRLabel92: TQRLabel;
    QRLabel113: TQRLabel;
    QRLabel115: TQRLabel;
    IBTORCAMENTOCB58: TIBStringField;
    IBTORCAMENTOCB59: TIBStringField;
    IBQORCAMENTOCB58: TIBStringField;
    IBQORCAMENTOCB59: TIBStringField;
    QRLabel23: TQRLabel;
    QRLabel24: TQRLabel;
    QRLabel75: TQRLabel;
    QRLabel118: TQRLabel;
    QRShape1: TQRShape;
    QRLabel57: TQRLabel;
    QRLabel119: TQRLabel;
    IBTORCAMENTOCB60: TIBStringField;
    IBTORCAMENTOCB61: TIBStringField;
    IBTORCAMENTOCB62: TIBStringField;
    IBTORCAMENTOCB63: TIBStringField;
    IBTORCAMENTOCB64: TIBStringField;
    IBTORCAMENTOCB65: TIBStringField;
    IBTORCAMENTOCB66: TIBStringField;
    IBTORCAMENTOCB67: TIBStringField;
    IBTORCAMENTOCB68: TIBStringField;
    IBTORCAMENTOCB69: TIBStringField;
    IBTORCAMENTOCB70: TIBStringField;
    IBQORCAMENTOCB60: TIBStringField;
    IBQORCAMENTOCB61: TIBStringField;
    IBQORCAMENTOCB62: TIBStringField;
    IBQORCAMENTOCB63: TIBStringField;
    IBQORCAMENTOCB64: TIBStringField;
    IBQORCAMENTOCB65: TIBStringField;
    IBQORCAMENTOCB66: TIBStringField;
    IBQORCAMENTOCB67: TIBStringField;
    IBQORCAMENTOCB68: TIBStringField;
    IBQORCAMENTOCB69: TIBStringField;
    IBQORCAMENTOCB70: TIBStringField;
    procedure IBTable1AfterPost(DataSet: TDataSet);
    procedure FormCreate(Sender: TObject);
    procedure IBTUsuariosAfterInsert(DataSet: TDataSet);
    procedure QuickRep100BeforePrint(Sender: TCustomQuickRep;
      var PrintReport: Boolean);
    procedure QuickRep1BeforePrint(Sender: TCustomQuickRep;
      var PrintReport: Boolean);
    procedure QuickRep2BeforePrint(Sender: TCustomQuickRep;
      var PrintReport: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fdm: Tfdm;

implementation

{$R *.dfm}

procedure Tfdm.FormCreate(Sender: TObject);
Var
HOST, ENDERECO: STRING;
Serial:DWord;
DirLen,Flags: DWord;
DLabel : Array[0..11] of Char;
NSERIAL : CARDINAL;
begin
MEMO1.Width := 10000;
EDIT2.Width := 10000;

//CONECTANDO AO BANCO DE DADOS
MEMO1.LINES.LoadFromFile('small.ini');

HOST :=  MEMO1.Lines[1];
ENDERECO := MEMO1.Lines[2];
DELETE(HOST,1,10);
DELETE(ENDERECO,1,11);
EDIT2.TEXT := HOST + ':' + ENDERECO + '\SMALL.FDB';

FDM.IBDatabase1.DatabaseName := EDIT2.Text;

FDM.IBDATABASE1.Connected := FALSE;
FDM.IBDATABASE1.DatabaseName := EDIT2.TEXT;
FDM.IBDATABASE1.Connected := TRUE;
end;

procedure Tfdm.IBTable1AfterPost(DataSet: TDataSet);
begin
FDM.IBTransaction1.CommitRetaining;
end;

procedure Tfdm.IBTUsuariosAfterInsert(DataSet: TDataSet);
begin
FDM.IBQGENUSUARIOS.Active := FALSE;
FDM.IBQGENUSUARIOS.SQL.Text := 'select gen_id(G_USUARIOS,1) from rdb$database';
FDM.IBQGENUSUARIOS.Active := TRUE;
IBTUSUARIOS.EDIT;
IBTUSUARIOSREGISTRO.Value := inttostr(IBQGENUSUARIOSGEN_ID.VALUE);
IBTUSUARIOSNIVEL.Value := '2';
IBTUSUARIOS.Post;
//IBTUSUARIOS.ApplyUpdates;
end;

procedure Tfdm.QuickRep100BeforePrint(Sender: TCustomQuickRep;
  var PrintReport: Boolean);
//VAR
//TROCO : STRING;
begin

QRCheckBox1.Checked := False;
QRCheckBox2.Checked := False;
QRCheckBox3.Checked := False;
QRCheckBox4.Checked := False;
QRCheckBox5.Checked := False;
QRCheckBox6.Checked := False;
QRCheckBox7.Checked := False;
QRCheckBox8.Checked := False;
QRCheckBox9.Checked := False;
QRCheckBox10.Checked := False;
QRCheckBox11.Checked := False;
QRCheckBox12.Checked := False;
QRCheckBox13.Checked := False;
QRCheckBox14.Checked := False;
QRCheckBox15.Checked := False;
QRCheckBox16.Checked := False;
QRCheckBox17.Checked := False;
QRCheckBox18.Checked := False;
QRCheckBox19.Checked := False;
QRCheckBox20.Checked := False;
QRCheckBox21.Checked := False;
QRCheckBox22.Checked := False;
QRCheckBox23.Checked := False;
QRCheckBox24.Checked := False;
QRCheckBox25.Checked := False;
QRCheckBox26.Checked := False;
QRCheckBox27.Checked := False;
QRCheckBox28.Checked := False;
QRCheckBox29.Checked := False;
QRCheckBox30.Checked := False;
QRCheckBox31.Checked := False;
QRCheckBox32.Checked := False;
QRCheckBox33.Checked := False;
QRCheckBox34.Checked := False;
QRCheckBox35.Checked := False;
QRCheckBox36.Checked := False;
QRCheckBox37.Checked := False;
QRCheckBox38.Checked := False;
QRCheckBox39.Checked := False;
QRCheckBox40.Checked := False;
QRCheckBox41.Checked := False;
QRCheckBox42.Checked := False;
QRCheckBox43.Checked := False;
QRCheckBox44.Checked := False;
QRCheckBox45.Checked := False;
QRCheckBox46.Checked := False;
QRCheckBox47.Checked := False;
QRCheckBox48.Checked := False;
QRCheckBox49.Checked := False;
QRCheckBox50.Checked := False;
QRCheckBox51.Checked := False;

IF IBQORCAMENTOCB1.TEXT = 'True' THEN QRCheckBox1.Checked := True;
IF IBQORCAMENTOCB2.TEXT = 'True' THEN QRCheckBox2.Checked := True;
IF IBQORCAMENTOCB3.TEXT = 'True' THEN QRCheckBox3.Checked := True;
IF IBQORCAMENTOCB4.TEXT = 'True' THEN QRCheckBox4.Checked := True;
IF IBQORCAMENTOCB5.TEXT = 'True' THEN QRCheckBox5.Checked := True;
IF IBQORCAMENTOCB6.TEXT = 'True' THEN QRCheckBox6.Checked := True;
IF IBQORCAMENTOCB7.TEXT = 'True' THEN QRCheckBox7.Checked := True;
IF IBQORCAMENTOCB8.TEXT = 'True' THEN QRCheckBox8.Checked := True;
IF IBQORCAMENTOCB9.TEXT = 'True' THEN QRCheckBox9.Checked := True;
IF IBQORCAMENTOCB10.TEXT = 'True' THEN QRCheckBox10.Checked := True;
IF IBQORCAMENTOCB11.TEXT = 'True' THEN QRCheckBox11.Checked := True;
IF IBQORCAMENTOCB12.TEXT = 'True' THEN QRCheckBox12.Checked := True;
IF IBQORCAMENTOCB13.TEXT = 'True' THEN QRCheckBox13.Checked := True;
IF IBQORCAMENTOCB14.TEXT = 'True' THEN QRCheckBox14.Checked := True;
IF IBQORCAMENTOCB15.TEXT = 'True' THEN QRCheckBox15.Checked := True;
IF IBQORCAMENTOCB16.TEXT = 'True' THEN QRCheckBox16.Checked := True;
IF IBQORCAMENTOCB17.TEXT = 'True' THEN QRCheckBox17.Checked := True;
IF IBQORCAMENTOCB18.TEXT = 'True' THEN QRCheckBox18.Checked := True;
IF IBQORCAMENTOCB19.TEXT = 'True' THEN QRCheckBox19.Checked := True;
IF IBQORCAMENTOCB20.TEXT = 'True' THEN QRCheckBox20.Checked := True;
IF IBQORCAMENTOCB21.TEXT = 'True' THEN QRCheckBox21.Checked := True;
IF IBQORCAMENTOCB22.TEXT = 'True' THEN QRCheckBox22.Checked := True;
IF IBQORCAMENTOCB23.TEXT = 'True' THEN QRCheckBox23.Checked := True;
IF IBQORCAMENTOCB24.TEXT = 'True' THEN QRCheckBox24.Checked := True;
IF IBQORCAMENTOCB25.TEXT = 'True' THEN QRCheckBox25.Checked := True;
IF IBQORCAMENTOCB26.TEXT = 'True' THEN QRCheckBox26.Checked := True;
IF IBQORCAMENTOCB27.TEXT = 'True' THEN QRCheckBox27.Checked := True;
IF IBQORCAMENTOCB28.TEXT = 'True' THEN QRCheckBox28.Checked := True;
IF IBQORCAMENTOCB29.TEXT = 'True' THEN QRCheckBox29.Checked := True;
IF IBQORCAMENTOCB30.TEXT = 'True' THEN QRCheckBox30.Checked := True;
IF IBQORCAMENTOCB31.TEXT = 'True' THEN QRCheckBox31.Checked := True;
IF IBQORCAMENTOCB32.TEXT = 'True' THEN QRCheckBox32.Checked := True;
IF IBQORCAMENTOCB33.TEXT = 'True' THEN QRCheckBox33.Checked := True;
IF IBQORCAMENTOCB34.TEXT = 'True' THEN QRCheckBox34.Checked := True;
IF IBQORCAMENTOCB35.TEXT = 'True' THEN QRCheckBox35.Checked := True;
IF IBQORCAMENTOCB36.TEXT = 'True' THEN QRCheckBox36.Checked := True;
IF IBQORCAMENTOCB37.TEXT = 'True' THEN QRCheckBox37.Checked := True;
IF IBQORCAMENTOCB38.TEXT = 'True' THEN QRCheckBox38.Checked := True;
IF IBQORCAMENTOCB39.TEXT = 'True' THEN QRCheckBox39.Checked := True;
IF IBQORCAMENTOCB40.TEXT = 'True' THEN QRCheckBox40.Checked := True;
IF IBQORCAMENTOCB41.TEXT = 'True' THEN QRCheckBox41.Checked := True;
IF IBQORCAMENTOCB42.TEXT = 'True' THEN QRCheckBox42.Checked := True;
IF IBQORCAMENTOCB43.TEXT = 'True' THEN QRCheckBox43.Checked := True;
IF IBQORCAMENTOCB44.TEXT = 'True' THEN QRCheckBox44.Checked := True;
IF IBQORCAMENTOCB45.TEXT = 'True' THEN QRCheckBox45.Checked := True;
IF IBQORCAMENTOCB46.TEXT = 'True' THEN QRCheckBox46.Checked := True;
IF IBQORCAMENTOCB47.TEXT = 'True' THEN QRCheckBox47.Checked := True;
IF IBQORCAMENTOCB48.TEXT = 'True' THEN QRCheckBox48.Checked := True;
IF IBQORCAMENTOCB49.TEXT = 'True' THEN QRCheckBox49.Checked := True;
IF IBQORCAMENTOCB50.TEXT = 'True' THEN QRCheckBox50.Checked := True;
IF IBQORCAMENTOCB51.TEXT = 'True' THEN QRCheckBox51.Checked := True;
                            
{//DEIXANDO AS FORMAS DE PAGAMENTO INVISÍVEIS, E DEIXAR APARECENDO APENAS A SELECIONADA PELO CLIENTE
QRLABEL2.CAPTION := '';     
QRDBTEXT7.DATAFIELD := '';
QRLABEL11.CAPTION := '';
QRDBTEXT8.DATAFIELD := '';
QRLABEL12.CAPTION := '';
QRDBTEXT9.DATAFIELD := '';

IF IBQORCAMENTOB1.Value > 0
  THEN
    BEGIN
      QRLABEL2.CAPTION := 'Crédito:    R$';
      QRDBTEXT7.DATAFIELD := 'B1';
    END;

IF IBQORCAMENTOB2.Value > 0
  THEN
    BEGIN
      QRLABEL11.CAPTION := 'Débito:     R$';
      QRDBTEXT8.DATAFIELD := 'B2';
    END;

IF IBQORCAMENTOB3.Value > 0
  THEN
    BEGIN
      QRLABEL12.CAPTION := 'Dinheiro:   R$';
      QRDBTEXT9.DATAFIELD := 'B3';
    END;

//QRLABEL29.Caption := FORMATFLOAT('0.00', FDM.IBQORCAMENTOB1.VALUE + FDM.IBQORCAMENTOB2.VALUE + FDM.IBQORCAMENTOB3.VALUE + FDM.IBQORCAMENTODESCONTO.VALUE - FDM.IBQORCAMENTOTOTAL.Value);
//O ALEX PEDIU PRA TROCAR A FUNÇÃO DO CAMPO TROCO, DE FINANCEIRO PARA O VALOR DO TROCO LEVADO PARA A ENTREGA

TRY
TROCO := StringReplace(FDM.IBQORCAMENTOTROCO.Value, '.', ',', [rfReplaceAll, rfIgnoreCase]);
TROCO := StringReplace(TROCO, 'R$', '', [rfReplaceAll, rfIgnoreCase]);
TROCO := StringReplace(TROCO, ' ', '', [rfReplaceAll, rfIgnoreCase]);

QRLABEL29.Caption := FORMATFLOAT('0.00', STRTOFLOAT(TROCO) - FDM.IBQORCAMENTOTOTAL.Value);
EXCEPT

END;

QRLABEL20.Caption := FORMATFLOAT('0.00', FDM.IBQORCAMENTOB1.VALUE + FDM.IBQORCAMENTOB2.VALUE + FDM.IBQORCAMENTOB3.VALUE);

QRLABEL44.Caption := FDM.IBQORCAMENTOOBSERVACAO.VALUE;
QRLABEL42.Caption := FDM.IBQORCAMENTOFORMA.VALUE;

fDM.IBQCLIFOR.ACTIVE := FALSE;
fDM.IBQCLIFOR.SQL.Text := 'SELECT * FROM CLIFOR WHERE NOME = ' + #39 + FDM.IBQORCAMENTOCLIENTE.VALUE + #39;
fDM.IBQCLIFOR.ACTIVE := TRUE;
}
end;

procedure Tfdm.QuickRep1BeforePrint(Sender: TCustomQuickRep;
  var PrintReport: Boolean);
VAR
TROCO : STRING;
begin

IF IBQORCAMENTOOPERACAO.Value = 'LOJA' THEN QRLABEL89.CAPTION := 'TAÇA';
IF IBQORCAMENTOOPERACAO.Value = 'LOJA' THEN QRLABEL91.CAPTION := 'VIAGEM';
IF IBQORCAMENTOOPERACAO.Value = 'DELIVERY' THEN QRLABEL89.CAPTION := 'DELIVERY';
IF IBQORCAMENTOOPERACAO.Value = 'DELIVERY' THEN QRLABEL91.CAPTION := 'IFOOD';


//DEIXANDO AS FORMAS DE PAGAMENTO INVISÍVEIS, E DEIXAR APARECENDO APENAS A SELECIONADA PELO CLIENTE
//QRLABEL118.CAPTION := '';
//QRDBTEXT14.DATAFIELD := '';
//QRLABEL119.CAPTION := '';
//QRDBTEXT25.DATAFIELD := '';
//QRLABEL120.CAPTION := '';
//QRDBTEXT26.DATAFIELD := '';
{
IF IBQORCAMENTOB1.Value > 0
  THEN
    BEGIN
      QRLABEL118.CAPTION := 'Crédito:    R$';
      QRDBTEXT14.DATAFIELD := 'B1';
    END;

IF IBQORCAMENTOB2.Value > 0
  THEN
    BEGIN
      QRLABEL119.CAPTION := 'Débito:     R$';
      QRDBTEXT25.DATAFIELD := 'B2';
    END;

IF IBQORCAMENTOB3.Value > 0
  THEN
    BEGIN
      QRLABEL120.CAPTION := 'Dinheiro:   R$';
      QRDBTEXT26.DATAFIELD := 'B3';
    END;
}
QRLABEL165.CAPTION := '0,00';

TRY
  TROCO := StringReplace(FDM.IBQORCAMENTOTROCO.Value, '.', ',', [rfReplaceAll, rfIgnoreCase]);
  TROCO := StringReplace(TROCO, 'R$', '', [rfReplaceAll, rfIgnoreCase]);
  TROCO := StringReplace(TROCO, ' ', '', [rfReplaceAll, rfIgnoreCase]);

  //QRLABEL28.Caption := FORMATFLOAT('0.00', STRTOFLOAT(TROCO) - FDM.IBQORCAMENTOTOTAL.Value);
//  if STRTOFLOAT(TROCO) > 0 then QRLABEL165.Caption := FORMATFLOAT('0.00', STRTOFLOAT(TROCO) - FDM.IBQORCAMENTOTOTAL.Value);
  if STRTOFLOAT(TROCO) > 0 then QRLABEL165.Caption := FORMATFLOAT('0.00', STRTOFLOAT(TROCO) - FDM.IBQORCAMENTOTOTAL.Value + FDM.IBQORCAMENTODESCONTO.Value);
  QRLABEL127.Caption := FORMATFLOAT('0.00', STRTOFLOAT(TROCO));

  IF FDM.IBQORCAMENTOCB50.Value = 'True' THEN QRPCHECKBOX1.CHECKED := TRUE ELSE QRPCHECKBOX1.CHECKED := FALSE;
  IF FDM.IBQORCAMENTOCB51.Value = 'True' THEN QRPCHECKBOX2.CHECKED := TRUE ELSE QRPCHECKBOX2.CHECKED := FALSE;

EXCEPT

END;

QRLABEL163.CAPTION := '0,00';
IF FDM.IBQORCAMENTOCB56.VALUE = 'True' THEN QRLABEL163.CAPTION := '2,00';
IF FDM.IBQORCAMENTOCB57.VALUE = 'True' THEN QRLABEL163.CAPTION := '3,00';

//Totais
QRLABEL113.Caption := FORMATFLOAT('0.00', FDM.IBQORCAMENTOTOTAL.Value);
IF FDM.IBQORCAMENTOCB56.VALUE = 'True' THEN QRLABEL113.Caption := FORMATFLOAT('0.00', FDM.IBQORCAMENTOTOTAL.Value - 2);
IF FDM.IBQORCAMENTOCB57.VALUE = 'True' THEN QRLABEL113.Caption := FORMATFLOAT('0.00', FDM.IBQORCAMENTOTOTAL.Value - 3);
QRLABEL115.Caption := FORMATFLOAT('0.00', FDM.IBQORCAMENTOTOTAL.Value - FDM.IBQORCAMENTODESCONTO.Value);

//QRLABEL125.Caption := FORMATFLOAT('0.00', FDM.IBQORCAMENTOB1.VALUE + FDM.IBQORCAMENTOB2.VALUE + FDM.IBQORCAMENTOB3.VALUE);

QRLABEL130.Caption := FDM.IBQORCAMENTOOBSERVACAO.VALUE;
QRLABEL131.Caption := FDM.IBQORCAMENTOFORMA.VALUE;

fDM.IBQCLIFOR.ACTIVE := FALSE;
fDM.IBQCLIFOR.SQL.Text := 'SELECT * FROM CLIFOR WHERE NOME = ' + #39 + FDM.IBQORCAMENTOCLIENTE.VALUE + #39;
fDM.IBQCLIFOR.ACTIVE := TRUE;   

QRLABEL92.Caption := 'Telefone: ' + FDM.IBQCLIFORFONE.VALUE;
end;

procedure Tfdm.QuickRep2BeforePrint(Sender: TCustomQuickRep;
  var PrintReport: Boolean);
begin
fdm.QUICKREP2.Height := 320 + FDM.IBQORCAMENTO.RecordCount * 17;
end;

end.
